package com.bridge.androidtechnicaltest.feature.add_pupil.model

val countries = listOf(
    "Nigeria",
    "United States",
    "Canada",
    "Brazil",
    "Argentina",
    "United Kingdom",
    "Germany",
    "France",
    "Spain",
    "Italy",
    "South Africa",
    "Egypt",
    "Kenya",
    "Ethiopia",
    "Ghana",
    "Morocco",
    "China",
    "India",
    "Japan",
    "South Korea",
    "Indonesia",
    "Philippines",
    "Thailand",
    "Vietnam",
    "Australia",
    "New Zealand",
    "Russia",
    "Ukraine",
    "Poland",
    "Netherlands",
    "Belgium",
    "Sweden",
    "Norway",
    "Finland",
    "Denmark",
    "Switzerland",
    "Austria",
    "Turkey",
    "Saudi Arabia",
    "United Arab Emirates",
    "Qatar",
    "Kuwait",
    "Pakistan",
    "Bangladesh",
    "Sri Lanka",
    "Nepal",
    "Mexico",
    "Chile",
    "Colombia",
    "Peru",
).sortedBy { it }